# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11No9AIORNnTSbJfU9jTbJXi-4ehoNGT2
"""

# PART 1 — INSTALL REQUIRED PACKAGES


import sys
import subprocess
import os
import re
import warnings
import gc
import json
import time

warnings.filterwarnings("ignore")

print("=" * 90)
print("PART 1 — INSTALLING / CHECKING REQUIRED PACKAGES")
print("=" * 90)

required_packages = {
    "pandas": "pandas",
    "numpy": "numpy",
    "sklearn": "scikit-learn",
    "matplotlib": "matplotlib",
    "plotly": "plotly",
    "transformers": "transformers",
    "torch": "torch",
    "sentence_transformers": "sentence-transformers",
    "bertopic": "bertopic",
    "umap": "umap-learn",
    "hdbscan": "hdbscan",
    "xgboost": "xgboost",
    "shap": "shap",
    "lime": "lime",
    "streamlit": "streamlit"
}

for import_name, package_name in required_packages.items():

    try:
        __import__(import_name)
        print(f"✓ {package_name}")

    except ImportError:

        print(f"Installing {package_name}...")

        subprocess.run(
            [
                sys.executable,
                "-m",
                "pip",
                "install",
                "-q",
                package_name
            ],
            check=False
        )

print()
print("Package check complete.")



# PART 2 — IMPORT LIBRARIES


print()
print("=" * 90)
print("PART 2 — IMPORTING LIBRARIES")
print("=" * 90)

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import plotly.express as px

import torch

from transformers import pipeline

from sentence_transformers import SentenceTransformer

from bertopic import BERTopic
from umap import UMAP
from hdbscan import HDBSCAN

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    cross_val_score
)

from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)

from xgboost import XGBClassifier

import shap

from lime.lime_tabular import LimeTabularExplainer

print("✓ pandas")
print("✓ numpy")
print("✓ sklearn")
print("✓ transformers")
print("✓ torch")
print("✓ sentence-transformers")
print("✓ BERTopic")
print("✓ XGBoost")
print("✓ SHAP")
print("✓ LIME")

print()
print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():

    DEVICE = 0

    print(
        "GPU:",
        torch.cuda.get_device_name(0)
    )

else:

    DEVICE = -1

    print("GPU: CPU")



# PART 3 — LOAD REDDIT DATA


print()
print("=" * 90)
print("PART 3 — LOADING REDDIT DATA")
print("=" * 90)

DATA_PATH = "/content/reddit_1000_final.csv"

if not os.path.exists(DATA_PATH):

    raise FileNotFoundError(
        f"""
Could not find:

{DATA_PATH}

Please upload reddit_1000_final.csv to Google Colab.
"""
    )

reddit = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully.")
print("Shape:", reddit.shape)

print()
print("Columns:")
print(list(reddit.columns))



# PART 4 — BASIC DATA PREPARATION


print()
print("=" * 90)
print("PART 4 — BASIC DATA PREPARATION")
print("=" * 90)

if "text" not in reddit.columns:

    raise ValueError(
        "The dataset must contain a 'text' column."
    )

reddit["text"] = (
    reddit["text"]
    .fillna("")
    .astype(str)
)

if "post_id" not in reddit.columns:

    reddit["post_id"] = np.arange(
        1,
        len(reddit) + 1
    )

if "created_utc" in reddit.columns:

    reddit["created_utc"] = pd.to_datetime(
        reddit["created_utc"],
        errors="coerce",
        utc=True
    )

else:

    print(
        "WARNING: created_utc not found."
    )

    # Create sequential dates only so the pipeline can execute.
    # These are NOT real publication dates.
    reddit["created_utc"] = pd.date_range(
        start="2025-01-01",
        periods=len(reddit),
        freq="h",
        tz="UTC"
    )


# Numeric columns

numeric_candidates = [
    "score",
    "engagement",
    "word_count",
    "text_length",
    "num_comments",
    "comments",
    "upvotes",
    "views",
    "karma"
]

for col in numeric_candidates:

    if col in reddit.columns:

        reddit[col] = pd.to_numeric(
            reddit[col],
            errors="coerce"
        ).fillna(0)



# PART 5 — GENERAL CLEANING


print()
print("=" * 90)
print("PART 5 — GENERAL DATA CLEANING")
print("=" * 90)

before_cleaning = len(reddit)

# Remove empty text

reddit = reddit[
    reddit["text"]
    .str.strip()
    .str.len()
    > 0
].copy()


# Remove duplicate post IDs

if "post_id" in reddit.columns:

    before_duplicates = len(reddit)

    reddit = reddit.drop_duplicates(
        subset=["post_id"],
        keep="first"
    )

    print(
        "Duplicate post IDs removed:",
        before_duplicates - len(reddit)
    )

else:

    before_duplicates = len(reddit)

    reddit = reddit.drop_duplicates(
        subset=["text"],
        keep="first"
    )

    print(
        "Duplicate text posts removed:",
        before_duplicates - len(reddit)
    )


print(
    "Posts before cleaning:",
    before_cleaning
)

print(
    "Posts after cleaning:",
    len(reddit)
)



# PART 6 — TEXT CLEANING FOR BERTopic


print()
print("=" * 90)
print("PART 6 — TOPIC MODELLING TEXT CLEANING")
print("=" * 90)

STOPWORDS = {
    "a", "about", "above", "after", "again", "against", "all",
    "am", "an", "and", "any", "are", "aren", "as", "at",
    "be", "because", "been", "before", "being", "below",
    "between", "both", "but", "by", "can", "could", "did",
    "do", "does", "doing", "don", "down", "during", "each",
    "few", "for", "from", "further", "had", "has", "have",
    "having", "he", "her", "here", "hers", "herself", "him",
    "himself", "his", "how", "i", "if", "in", "into", "is",
    "it", "its", "itself", "just", "me", "more", "most",
    "my", "myself", "no", "nor", "not", "now", "of", "off",
    "on", "once", "only", "or", "other", "our", "ours",
    "ourselves", "out", "over", "own", "same", "she", "should",
    "so", "some", "such", "than", "that", "the", "their",
    "theirs", "them", "themselves", "then", "there", "these",
    "they", "this", "those", "through", "to", "too", "under",
    "until", "up", "very", "was", "we", "were", "what",
    "when", "where", "which", "while", "who", "whom", "why",
    "will", "with", "would", "you", "your", "yours",
    "yourself", "yourselves"
}

DOMAIN_STOPWORDS = {
    "http",
    "https",
    "www",
    "com",
    "org",
    "net",
    "reddit",
    "redditcom",
    "post",
    "posts",
    "comment",
    "comments",
    "edit",
    "edited",
    "deleted",
    "removed",
    "amp",
    "gt",
    "lt",
    "nbsp",
    "imgur",
    "jpg",
    "jpeg",
    "png",
    "gif",
    "html",
    "url",
    "link",
    "source",
    "wwwredditcom"
}

ALL_STOPWORDS = STOPWORDS.union(
    DOMAIN_STOPWORDS
)


def clean_topic_text(text):

    text = str(text).lower()

    # URLs
    text = re.sub(
        r"https?://\S+|www\.\S+",
        " ",
        text
    )

    # Markdown links
    text = re.sub(
        r"\[([^\]]+)\]\([^)]+\)",
        r"\1",
        text
    )

    # Usernames
    text = re.sub(
        r"/u/\w+|u/\w+|@\w+",
        " ",
        text
    )

    # Subreddits
    text = re.sub(
        r"/r/\w+|r/\w+",
        " ",
        text
    )

    # HTML entities
    text = re.sub(
        r"&\w+;",
        " ",
        text
    )

    # Keep alphabetic characters
    text = re.sub(
        r"[^a-z\s]",
        " ",
        text
    )

    # Whitespace
    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    words = [
        word
        for word in text.split()
        if word not in ALL_STOPWORDS
        and len(word) >= 3
    ]

    return " ".join(words)


reddit["text_topic"] = (
    reddit["text"]
    .apply(clean_topic_text)
)

reddit = reddit[
    reddit["text_topic"].str.len() > 0
].copy()

reddit = reddit[
    reddit["text_topic"]
    .str.split()
    .str.len()
    >= 2
].copy()

print(
    "Usable documents:",
    len(reddit)
)



# PART 7 — BERT SENTIMENT


print()
print("=" * 90)
print("PART 7 — BERT SENTIMENT ANALYSIS")
print("=" * 90)

# BERT-based sentiment model.
#
# IMPORTANT:
# This is a BERT-base architecture fine-tuned for sentiment,
# rather than a generic un-fine-tuned BERT model.
#
# It produces 5-star sentiment, which we convert to:
# Negative / Neutral / Positive.

BERT_MODEL = (
    "nlptown/"
    "bert-base-multilingual-uncased-sentiment"
)

print(
    "Loading BERT sentiment model..."
)

bert_pipeline = pipeline(
    "sentiment-analysis",
    model=BERT_MODEL,
    tokenizer=BERT_MODEL,
    device=DEVICE,
    truncation=True,
    max_length=256
)

print("✓ BERT loaded")


def convert_bert_label(label):

    label = str(label).lower()

    if "1" in label or "2" in label:

        return "Negative"

    elif "3" in label:

        return "Neutral"

    elif "4" in label or "5" in label:

        return "Positive"

    return "Neutral"


def run_sentiment_model(
    model_pipeline,
    texts,
    batch_size=16
):

    results = []

    for start in range(
        0,
        len(texts),
        batch_size
    ):

        batch = texts[
            start:start + batch_size
        ]

        try:

            batch_results = model_pipeline(
                batch,
                batch_size=batch_size
            )

            results.extend(
                batch_results
            )

        except Exception as e:

            print(
                "Batch fallback:",
                str(e)[:100]
            )

            for text in batch:

                try:

                    result = model_pipeline(
                        text[:2000]
                    )[0]

                    results.append(
                        result
                    )

                except Exception:

                    results.append({
                        "label": "3 stars",
                        "score": 0.0
                    })

        processed = min(
            start + batch_size,
            len(texts)
        )

        if (
            start == 0
            or processed % 100 == 0
        ):

            print(
                f"Processed "
                f"{processed}/{len(texts)}"
            )

    return results


bert_results = run_sentiment_model(
    bert_pipeline,
    reddit["text"].tolist(),
    batch_size=16
)

reddit["bert_raw_label"] = [
    result["label"]
    for result in bert_results
]

reddit["bert_confidence"] = [
    float(result["score"])
    for result in bert_results
]

reddit["bert_sentiment"] = (
    reddit["bert_raw_label"]
    .apply(convert_bert_label)
)

print()
print(
    reddit["bert_sentiment"]
    .value_counts()
)



# PART 8 — RoBERTa SENTIMENT


print()
print("=" * 90)
print("PART 8 — RoBERTa SENTIMENT ANALYSIS")
print("=" * 90)

ROBERTA_MODEL = (
    "cardiffnlp/"
    "twitter-roberta-base-sentiment-latest"
)

print(
    "Loading RoBERTa..."
)

roberta_pipeline = pipeline(
    "sentiment-analysis",
    model=ROBERTA_MODEL,
    tokenizer=ROBERTA_MODEL,
    device=DEVICE,
    truncation=True,
    max_length=256
)

print("✓ RoBERTa loaded")


def convert_roberta_label(label):

    label = str(label).lower()

    if (
        "negative" in label
        or label == "label_0"
        or label == "0"
    ):

        return "Negative"

    elif (
        "neutral" in label
        or label == "label_1"
        or label == "1"
    ):

        return "Neutral"

    elif (
        "positive" in label
        or label == "label_2"
        or label == "2"
    ):

        return "Positive"

    return "Neutral"


roberta_results = run_sentiment_model(
    roberta_pipeline,
    reddit["text"].tolist(),
    batch_size=16
)

reddit["roberta_raw_label"] = [
    result["label"]
    for result in roberta_results
]

reddit["roberta_confidence"] = [
    float(result["score"])
    for result in roberta_results
]

reddit["roberta_sentiment"] = (
    reddit["roberta_raw_label"]
    .apply(convert_roberta_label)
)

print()
print(
    reddit["roberta_sentiment"]
    .value_counts()
)



# PART 9 — BERT VS RoBERTa COMPARISON


print()
print("=" * 90)
print("PART 9 — BERT VS RoBERTa COMPARISON")
print("=" * 90)

agreement = (
    reddit["bert_sentiment"]
    ==
    reddit["roberta_sentiment"]
)

agreement_rate = (
    agreement.mean() * 100
)

bert_mean_confidence = (
    reddit["bert_confidence"]
    .mean()
)

roberta_mean_confidence = (
    reddit["roberta_confidence"]
    .mean()
)

comparison = pd.DataFrame({

    "model": [
        "BERT",
        "RoBERTa"
    ],

    "mean_confidence": [
        bert_mean_confidence,
        roberta_mean_confidence
    ],

    "positive_posts": [
        (
            reddit["bert_sentiment"]
            == "Positive"
        ).sum(),

        (
            reddit["roberta_sentiment"]
            == "Positive"
        ).sum()
    ],

    "neutral_posts": [
        (
            reddit["bert_sentiment"]
            == "Neutral"
        ).sum(),

        (
            reddit["roberta_sentiment"]
            == "Neutral"
        ).sum()
    ],

    "negative_posts": [
        (
            reddit["bert_sentiment"]
            == "Negative"
        ).sum(),

        (
            reddit["roberta_sentiment"]
            == "Negative"
        ).sum()
    ]
})

print(
    comparison.to_string(
        index=False
    )
)

print()
print(
    f"Model agreement: "
    f"{agreement_rate:.2f}%"
)

print(
    f"BERT mean confidence: "
    f"{bert_mean_confidence:.4f}"
)

print(
    f"RoBERTa mean confidence: "
    f"{roberta_mean_confidence:.4f}"
)



if (
    roberta_mean_confidence
    >=
    bert_mean_confidence
):

    BEST_MODEL = "RoBERTa"

else:

    BEST_MODEL = "BERT"

print()
print(
    "Selected sentiment model:",
    BEST_MODEL
)



# PART 10 — FINAL SENTIMENT


print()
print("=" * 90)
print("PART 10 — FINAL SENTIMENT COLUMN")
print("=" * 90)

if BEST_MODEL == "RoBERTa":

    reddit["sentiment"] = (
        reddit["roberta_sentiment"]
    )

    reddit["sentiment_confidence"] = (
        reddit["roberta_confidence"]
    )

else:

    reddit["sentiment"] = (
        reddit["bert_sentiment"]
    )

    reddit["sentiment_confidence"] = (
        reddit["bert_confidence"]
    )


sentiment_score_map = {

    "Negative": -1,

    "Neutral": 0,

    "Positive": 1
}

reddit["sentiment_score"] = (
    reddit["sentiment"]
    .map(sentiment_score_map)
    .fillna(0)
)

print(
    reddit["sentiment"]
    .value_counts()
)



# PART 11 — SAVE SENTIMENT COMPARISON


sentiment_comparison_path = (
    "/content/reddit_sentiment_comparison.csv"
)

reddit[
    [
        "post_id",
        "text",
        "sentiment",
        "sentiment_score",
        "sentiment_confidence",
        "bert_sentiment",
        "bert_confidence",
        "roberta_sentiment",
        "roberta_confidence"
    ]
].to_csv(
    sentiment_comparison_path,
    index=False
)

print(
    "✓ Saved:",
    sentiment_comparison_path
)



# PART 12 — BERTopic EMBEDDINGS


print()
print("=" * 90)
print("PART 12 — BERTopic EMBEDDINGS")
print("=" * 90)

documents = (
    reddit["text_topic"]
    .tolist()
)

documents = [
    document[:1000]
    for document in documents
]

EMBEDDING_MODEL = (
    "sentence-transformers/"
    "all-MiniLM-L6-v2"
)

print(
    "Loading embedding model..."
)

embedding_model = SentenceTransformer(
    EMBEDDING_MODEL,
    device=(
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )
)

print(
    "✓ Embedding model loaded"
)



# PART 13 — BERTopic


print()
print("=" * 90)
print("PART 13 — BERTopic TOPIC MODELLING")
print("=" * 90)

umap_model = UMAP(
    n_neighbors=10,
    n_components=5,
    min_dist=0.0,
    metric="cosine",
    random_state=42
)

hdbscan_model = HDBSCAN(
    min_cluster_size=15,
    min_samples=5,
    metric="euclidean",
    cluster_selection_method="eom",
    prediction_data=True
)

topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    min_topic_size=15,
    top_n_words=8,
    n_gram_range=(1, 2),
    calculate_probabilities=False,
    verbose=True
)

topics, probabilities = (
    topic_model.fit_transform(
        documents
    )
)

reddit["topic_id"] = topics

print()
print(
    "✓ BERTopic training complete"
)



# PART 14 — TOPIC INFORMATION


print()
print("=" * 90)
print("PART 14 — TOPIC INFORMATION")
print("=" * 90)

topic_info = (
    topic_model
    .get_topic_info()
)

print(
    topic_info[
        [
            "Topic",
            "Count",
            "Name"
        ]
    ]
    .head(20)
    .to_string(
        index=False
    )
)



# PART 15 — REMOVE BERTopic OUTLIERS


reddit_topic = reddit[
    reddit["topic_id"] != -1
].copy()

print()
print(
    "Valid topic posts:",
    len(reddit_topic)
)

print(
    "Outlier posts:",
    (
        reddit["topic_id"]
        == -1
    ).sum()
)



# PART 16 — HUMAN-READABLE TOPIC NAMES


print()
print("=" * 90)
print("PART 16 — TOPIC INTERPRETATION")
print("=" * 90)


def get_topic_keywords(topic_id):

    words = topic_model.get_topic(
        topic_id
    )

    if not words:

        return ""

    terms = [

        word

        for word, score in words[:5]

        if word not in ALL_STOPWORDS

        and len(word) >= 3

    ]

    return " / ".join(terms)


topic_names = {}

valid_topic_ids = sorted(
    reddit_topic["topic_id"]
    .unique()
)

for topic_id in valid_topic_ids:

    topic_names[
        topic_id
    ] = get_topic_keywords(
        topic_id
    )

for topic_id in valid_topic_ids:

    if not topic_names.get(
        topic_id
    ):

        topic_names[
            topic_id
        ] = f"Topic {topic_id}"


reddit_topic["topic_name"] = (
    reddit_topic["topic_id"]
    .map(topic_names)
)

print()
print(
    "Discovered topics:"
)

for topic_id in valid_topic_ids:

    count = (
        reddit_topic["topic_id"]
        == topic_id
    ).sum()

    print(
        f"Topic {topic_id}: "
        f"{topic_names[topic_id]} "
        f"({count} posts)"
    )



# PART 17 — TEMPORAL FEATURES


print()
print("=" * 90)
print("PART 17 — TEMPORAL TREND ANALYSIS")
print("=" * 90)

reddit_topic["created_utc"] = (
    pd.to_datetime(
        reddit_topic["created_utc"],
        errors="coerce",
        utc=True
    )
)

reddit_topic = (
    reddit_topic
    .dropna(
        subset=["created_utc"]
    )
    .copy()
)

reddit_topic["week_start"] = (
    reddit_topic["created_utc"]
    .dt.to_period("W-SUN")
    .dt.start_time
)

reddit_topic["week"] = (
    reddit_topic["week_start"]
    .dt.strftime("%Y-%m-%d")
)


# Engagement

if "engagement" not in reddit_topic.columns:

    reddit_topic["engagement"] = 0

reddit_topic["engagement"] = (
    pd.to_numeric(
        reddit_topic["engagement"],
        errors="coerce"
    )
    .fillna(0)
)

reddit_topic["engagement_positive"] = (
    reddit_topic["engagement"]
    .clip(lower=0)
)


print(
    "Number of observed weeks:",
    reddit_topic["week"].nunique()
)



# PART 18 — TOPIC STATISTICS


print()
print("=" * 90)
print("PART 18 — TOPIC STATISTICS")
print("=" * 90)

topic_stats = (
    reddit_topic
    .groupby(
        [
            "topic_id",
            "topic_name"
        ]
    )
    .agg(

        post_count=(
            "topic_id",
            "size"
        ),

        total_engagement=(
            "engagement_positive",
            "sum"
        ),

        average_engagement=(
            "engagement_positive",
            "mean"
        ),

        average_sentiment=(
            "sentiment_score",
            "mean"
        ),

        average_confidence=(
            "sentiment_confidence",
            "mean"
        )
    )
    .reset_index()
)



# PART 19 — WEEKLY TOPIC GROWTH


weekly_counts = (
    reddit_topic
    .groupby(
        [
            "topic_id",
            "week"
        ]
    )
    .size()
    .reset_index(
        name="weekly_posts"
    )
)

growth_records = []

for topic_id in topic_stats[
    "topic_id"
]:

    values = (
        weekly_counts[
            weekly_counts["topic_id"]
            == topic_id
        ]
        .sort_values("week")
    )

    if len(values) == 0:

        recent_count = 0
        previous_count = 0
        growth = 0

    elif len(values) == 1:

        recent_count = int(
            values[
                "weekly_posts"
            ].iloc[-1]
        )

        previous_count = 0

        growth = float(
            recent_count
        )

    else:

        recent_count = int(
            values[
                "weekly_posts"
            ].iloc[-1]
        )

        previous_count = int(
            values[
                "weekly_posts"
            ].iloc[-2]
        )

        growth = float(
            recent_count
            -
            previous_count
        )

    growth_records.append({

        "topic_id": topic_id,

        "recent_count": recent_count,

        "previous_count": previous_count,

        "growth": growth
    })

growth_df = pd.DataFrame(
    growth_records
)

topic_stats = topic_stats.merge(
    growth_df,
    on="topic_id",
    how="left"
)

topic_stats["topic_name"] = (
    topic_stats["topic_id"]
    .map(topic_names)
)



# PART 20 — EXPLAINABLE TREND SCORE


print()
print("=" * 90)
print("PART 20 — EXPLAINABLE TREND SCORE")
print("=" * 90)


def minmax_series(series):

    series = pd.to_numeric(
        series,
        errors="coerce"
    ).fillna(0)

    minimum = series.min()

    maximum = series.max()

    if maximum == minimum:

        return pd.Series(
            0.5,
            index=series.index
        )

    return (
        (series - minimum)
        /
        (maximum - minimum)
    )


topic_stats[
    "frequency_score"
] = minmax_series(
    topic_stats["post_count"]
)

topic_stats[
    "growth_score"
] = minmax_series(
    topic_stats["growth"]
)

topic_stats[
    "engagement_score"
] = minmax_series(
    topic_stats["total_engagement"]
)

topic_stats[
    "sentiment_score"
] = (
    topic_stats["average_sentiment"]
    + 1
) / 2

topic_stats[
    "sentiment_score"
] = topic_stats[
    "sentiment_score"
].clip(
    0,
    1
)


# Explainable weighted score

topic_stats["trend_score"] = (

    0.30
    *
    topic_stats[
        "frequency_score"
    ]

    +

    0.30
    *
    topic_stats[
        "growth_score"
    ]

    +

    0.25
    *
    topic_stats[
        "engagement_score"
    ]

    +

    0.15
    *
    topic_stats[
        "sentiment_score"
    ]

) * 100


def trend_category(score):

    if score >= 60:

        return "Strong Consumer Trend"

    elif score >= 40:

        return "Emerging Trend"

    elif score >= 20:

        return "Moderate Trend"

    else:

        return "Low / Stable Trend"


topic_stats[
    "trend_category"
] = (
    topic_stats[
        "trend_score"
    ]
    .apply(
        trend_category
    )
)



# PART 21 — TREND RANKING


ranking = (
    topic_stats
    .sort_values(
        "trend_score",
        ascending=False
    )
    .reset_index(
        drop=True
    )
)

ranking["rank"] = (
    np.arange(
        1,
        len(ranking) + 1
    )
)

ranking["growth_rate"] = (
    ranking["growth"]
)

print()
print(
    "TOP CONSUMER TRENDS"
)

print(
    ranking[
        [
            "rank",
            "topic_name",
            "post_count",
            "growth_rate",
            "trend_score",
            "trend_category"
        ]
    ]
    .head(15)
    .to_string(
        index=False
    )
)



# PART 22 — FEATURE ENGINEERING FOR ORGANIC / ARTIFICIAL CLASSIFICATION


print()
print("=" * 90)
print("PART 22 — ORGANIC VS ARTIFICIAL TREND FEATURE ENGINEERING")
print("=" * 90)

organic = reddit_topic.copy()




# Feature 1 — Engagement

organic["feature_engagement"] = (
    pd.to_numeric(
        organic["engagement_positive"],
        errors="coerce"
    )
    .fillna(0)
)


# Feature 2 — Score

if "score" in organic.columns:

    organic["feature_score"] = (
        pd.to_numeric(
            organic["score"],
            errors="coerce"
        )
        .fillna(0)
        .clip(lower=0)
    )

else:

    organic["feature_score"] = 0


# Feature 3 — Comment activity

if "num_comments" in organic.columns:

    organic["feature_comments"] = (
        pd.to_numeric(
            organic["num_comments"],
            errors="coerce"
        )
        .fillna(0)
        .clip(lower=0)
    )

elif "comments" in organic.columns:

    organic["feature_comments"] = (
        pd.to_numeric(
            organic["comments"],
            errors="coerce"
        )
        .fillna(0)
        .clip(lower=0)
    )

else:

    organic["feature_comments"] = 0


# Feature 4 — Text length

organic["feature_text_length"] = (
    organic["text"]
    .str.len()
    .fillna(0)
)


# Feature 5 — Word count

organic["feature_word_count"] = (
    organic["text"]
    .str.split()
    .str.len()
    .fillna(0)
)


# Feature 6 — Sentiment confidence

organic["feature_sentiment_confidence"] = (
    pd.to_numeric(
        organic[
            "sentiment_confidence"
        ],
        errors="coerce"
    )
    .fillna(0)
)


# Feature 7 — Sentiment strength

organic["feature_sentiment_strength"] = (
    organic[
        "sentiment_score"
    ]
    .abs()
)


# Feature 8 — Topic frequency

topic_frequency_map = (
    organic[
        "topic_id"
    ]
    .value_counts()
    .to_dict()
)

organic[
    "feature_topic_frequency"
] = (
    organic["topic_id"]
    .map(topic_frequency_map)
    .fillna(0)
)


# Feature 9 — Topic growth

topic_growth_map = (
    topic_stats
    .set_index(
        "topic_id"
    )[
        "growth"
    ]
    .to_dict()
)

organic[
    "feature_topic_growth"
] = (
    organic["topic_id"]
    .map(topic_growth_map)
    .fillna(0)
)


# Feature 10 — Topic engagement

topic_engagement_map = (
    topic_stats
    .set_index(
        "topic_id"
    )[
        "total_engagement"
    ]
    .to_dict()
)

organic[
    "feature_topic_engagement"
] = (
    organic["topic_id"]
    .map(topic_engagement_map)
    .fillna(0)
)



# PART 23 — DUPLICATE / REPETITION SIGNAL


print()
print(
    "Calculating text repetition signal..."
)


organic[
    "text_normalised"
] = (
    organic["text_topic"]
    .str.lower()
    .str.replace(
        r"\s+",
        " ",
        regex=True
    )
    .str.strip()
)

text_frequency = (
    organic[
        "text_normalised"
    ]
    .value_counts()
)

organic[
    "feature_text_repetition"
] = (
    organic[
        "text_normalised"
    ]
    .map(text_frequency)
    .fillna(1)
)



# PART 24 — TEMPORAL BURST SIGNAL


# Number of posts in the same topic/week

topic_week_frequency = (
    organic
    .groupby(
        [
            "topic_id",
            "week"
        ]
    )
    .size()
    .reset_index(
        name="topic_week_posts"
    )
)

organic = organic.merge(
    topic_week_frequency,
    on=[
        "topic_id",
        "week"
    ],
    how="left"
)

organic[
    "feature_temporal_burst"
] = (
    organic[
        "topic_week_posts"
    ]
    .fillna(0)
)



# PART 25 — BUILD AMPLIFICATION SCORE


print()
print("=" * 90)
print("PART 25 — AMPLIFICATION SIGNAL")
print("=" * 90)


def safe_minmax(series):

    series = pd.to_numeric(
        series,
        errors="coerce"
    ).fillna(0)

    min_value = series.min()

    max_value = series.max()

    if max_value == min_value:

        return pd.Series(
            0.0,
            index=series.index
        )

    return (
        (series - min_value)
        /
        (max_value - min_value)
    )


organic[
    "norm_engagement"
] = safe_minmax(
    organic[
        "feature_engagement"
    ]
)

organic[
    "norm_score"
] = safe_minmax(
    organic[
        "feature_score"
    ]
)

organic[
    "norm_comments"
] = safe_minmax(
    organic[
        "feature_comments"
    ]
)

organic[
    "norm_repetition"
] = safe_minmax(
    organic[
        "feature_text_repetition"
    ]
)

organic[
    "norm_burst"
] = safe_minmax(
    organic[
        "feature_temporal_burst"
    ]
)




organic[
    "amplification_score"
] = (

    0.30
    *
    organic[
        "norm_engagement"
    ]

    +

    0.20
    *
    organic[
        "norm_score"
    ]

    +

    0.15
    *
    organic[
        "norm_comments"
    ]

    +

    0.15
    *
    organic[
        "norm_repetition"
    ]

    +

    0.20
    *
    organic[
        "norm_burst"
    ]
)



# PART 26 — ORGANIC / ARTIFICIAL TARGET


print()
print("=" * 90)
print("PART 26 — ORGANIC / ARTIFICIAL CLASSIFICATION TARGET")
print("=" * 90)


# -------------------------------------------------------------------------
# FIRST CHECK WHETHER THE DATASET ALREADY HAS A REAL LABEL
# -------------------------------------------------------------------------

possible_label_columns = [

    "organic_artificial",

    "trend_type",

    "trend_label",

    "trend_class",

    "label",

    "class",

    "organic",

    "is_organic",

    "artificial",

    "is_artificial"
]

existing_label = None

for col in possible_label_columns:

    if col in organic.columns:

        existing_label = col

        break


if existing_label is not None:

    print(
        "Existing classification label found:",
        existing_label
    )

    raw_labels = (
        organic[
            existing_label
        ]
        .astype(str)
        .str.lower()
        .str.strip()
    )

    def convert_existing_label(value):

        if value in [
            "organic",
            "0",
            "false",
            "natural"
        ]:

            return 0

        if value in [
            "artificial",
            "1",
            "true",
            "amplified",
            "manipulated"
        ]:

            return 1

        return np.nan

    organic[
        "artificial_label"
    ] = (
        raw_labels
        .apply(
            convert_existing_label
        )
    )

    organic = organic.dropna(
        subset=[
            "artificial_label"
        ]
    ).copy()

    organic[
        "artificial_label"
    ] = organic[
        "artificial_label"
    ].astype(int)

    LABEL_SOURCE = (
        f"Existing dataset label: "
        f"{existing_label}"
    )


else:

    print(
        "No human-labelled organic/artificial column found."
    )

    print(
        "Creating transparent weak/proxy labels."
    )

    # Use the 75th percentile as the amplification threshold.
    threshold = (
        organic[
            "amplification_score"
        ]
        .quantile(0.75)
    )

    organic[
        "artificial_label"
    ] = (
        organic[
            "amplification_score"
        ]
        >= threshold
    ).astype(int)

    LABEL_SOURCE = (
        "Weak proxy label based on "
        "engagement, score, comments, "
        "repetition and temporal burst signals."
    )


print()
print(
    "LABEL SOURCE:"
)

print(
    LABEL_SOURCE
)




print()
print(
    "Organic/artificial label distribution:"
)

print(
    organic[
        "artificial_label"
    ]
    .value_counts()
    .rename(
        index={
            0: "Organic",
            1: "Artificial"
        }
    )
)



# PART 27 — MACHINE LEARNING FEATURES


print()
print("=" * 90)
print("PART 27 — MACHINE LEARNING FEATURES")
print("=" * 90)

FEATURE_COLUMNS = [

    "feature_engagement",

    "feature_score",

    "feature_comments",

    "feature_text_length",

    "feature_word_count",

    "feature_sentiment_confidence",

    "feature_sentiment_strength",

    "feature_topic_frequency",

    "feature_topic_growth",

    "feature_topic_engagement",

    "feature_text_repetition",

    "feature_temporal_burst"
]


# Make sure all features exist

for col in FEATURE_COLUMNS:

    if col not in organic.columns:

        organic[col] = 0


X = (
    organic[
        FEATURE_COLUMNS
    ]
    .replace(
        [np.inf, -np.inf],
        np.nan
    )
    .fillna(0)
)

y = organic[
    "artificial_label"
].astype(int)


print(
    "Feature matrix shape:",
    X.shape
)

print(
    "Target shape:",
    y.shape
)



# PART 28 — CHECK CLASS BALANCE


print()
print("=" * 90)
print("PART 28 — CLASS BALANCE")
print("=" * 90)

print(
    y.value_counts()
)

if y.nunique() < 2:

    raise ValueError(
        """
The organic/artificial target contains only one class.

The classifier cannot be trained.

Please check your dataset's organic/artificial labels
or adjust the weak-label threshold.
"""
    )



# PART 29 — TRAIN TEST SPLIT


print()
print("=" * 90)
print("PART 29 — TRAIN / TEST SPLIT")
print("=" * 90)

X_train, X_test, y_train, y_test = (
    train_test_split(
        X,
        y,
        test_size=0.20,
        random_state=42,
        stratify=y
    )
)

print(
    "Training samples:",
    len(X_train)
)

print(
    "Testing samples:",
    len(X_test)
)



# PART 30 — RANDOM FOREST


print()
print("=" * 90)
print("PART 30 — RANDOM FOREST")
print("=" * 90)

rf_model = RandomForestClassifier(

    n_estimators=300,

    max_depth=None,

    min_samples_split=2,

    min_samples_leaf=1,

    random_state=42,

    class_weight="balanced",

    n_jobs=-1
)

rf_model.fit(
    X_train,
    y_train
)

rf_predictions = (
    rf_model
    .predict(X_test)
)

rf_probabilities = (
    rf_model
    .predict_proba(X_test)[:, 1]
)


# Metrics

rf_accuracy = accuracy_score(
    y_test,
    rf_predictions
)

rf_precision = precision_score(
    y_test,
    rf_predictions,
    zero_division=0
)

rf_recall = recall_score(
    y_test,
    rf_predictions,
    zero_division=0
)

rf_f1 = f1_score(
    y_test,
    rf_predictions,
    zero_division=0
)

try:

    rf_auc = roc_auc_score(
        y_test,
        rf_probabilities
    )

except Exception:

    rf_auc = np.nan


print()
print("RANDOM FOREST RESULTS")

print(
    f"Accuracy : {rf_accuracy:.4f}"
)

print(
    f"Precision: {rf_precision:.4f}"
)

print(
    f"Recall   : {rf_recall:.4f}"
)

print(
    f"F1-score : {rf_f1:.4f}"
)

print(
    f"ROC-AUC  : {rf_auc:.4f}"
    if not np.isnan(rf_auc)
    else "ROC-AUC  : N/A"
)

print()
print(
    classification_report(
        y_test,
        rf_predictions,
        target_names=[
            "Organic",
            "Artificial"
        ],
        zero_division=0
    )
)



# PART 31 — XGBOOST


print()
print("=" * 90)
print("PART 31 — XGBOOST")
print("=" * 90)

xgb_model = XGBClassifier(

    n_estimators=300,

    max_depth=5,

    learning_rate=0.05,

    subsample=0.8,

    colsample_bytree=0.8,

    objective="binary:logistic",

    eval_metric="logloss",

    random_state=42,

    n_jobs=-1
)

xgb_model.fit(
    X_train,
    y_train
)

xgb_predictions = (
    xgb_model
    .predict(X_test)
)

xgb_probabilities = (
    xgb_model
    .predict_proba(X_test)[:, 1]
)


# Metrics

xgb_accuracy = accuracy_score(
    y_test,
    xgb_predictions
)

xgb_precision = precision_score(
    y_test,
    xgb_predictions,
    zero_division=0
)

xgb_recall = recall_score(
    y_test,
    xgb_predictions,
    zero_division=0
)

xgb_f1 = f1_score(
    y_test,
    xgb_predictions,
    zero_division=0
)

try:

    xgb_auc = roc_auc_score(
        y_test,
        xgb_probabilities
    )

except Exception:

    xgb_auc = np.nan


print()
print("XGBOOST RESULTS")

print(
    f"Accuracy : {xgb_accuracy:.4f}"
)

print(
    f"Precision: {xgb_precision:.4f}"
)

print(
    f"Recall   : {xgb_recall:.4f}"
)

print(
    f"F1-score : {xgb_f1:.4f}"
)

print(
    f"ROC-AUC  : {xgb_auc:.4f}"
    if not np.isnan(xgb_auc)
    else "ROC-AUC  : N/A"
)

print()
print(
    classification_report(
        y_test,
        xgb_predictions,
        target_names=[
            "Organic",
            "Artificial"
        ],
        zero_division=0
    )
)



# PART 32 — MODEL COMPARISON


print()
print("=" * 90)
print("PART 32 — XGBOOST VS RANDOM FOREST COMPARISON")
print("=" * 90)

model_comparison = pd.DataFrame({

    "Model": [
        "Random Forest",
        "XGBoost"
    ],

    "Accuracy": [
        rf_accuracy,
        xgb_accuracy
    ],

    "Precision": [
        rf_precision,
        xgb_precision
    ],

    "Recall": [
        rf_recall,
        xgb_recall
    ],

    "F1": [
        rf_f1,
        xgb_f1
    ],

    "ROC_AUC": [
        rf_auc,
        xgb_auc
    ]
})

print(
    model_comparison
    .to_string(
        index=False
    )
)


# Select model using F1 as primary metric

if xgb_f1 >= rf_f1:

    BEST_CLASSIFIER = "XGBoost"

else:

    BEST_CLASSIFIER = "Random Forest"

print()
print(
    "BEST CLASSIFIER BASED ON F1:",
    BEST_CLASSIFIER
)



# PART 33 — PREDICT ORGANIC / ARTIFICIAL FOR ALL POSTS


print()
print("=" * 90)
print("PART 33 — ORGANIC / ARTIFICIAL PREDICTIONS")
print("=" * 90)

if BEST_CLASSIFIER == "XGBoost":

    organic[
        "predicted_probability_artificial"
    ] = xgb_model.predict_proba(
        X
    )[:, 1]

    organic[
        "predicted_class"
    ] = xgb_model.predict(
        X
    )

else:

    organic[
        "predicted_probability_artificial"
    ] = rf_model.predict_proba(
        X
    )[:, 1]

    organic[
        "predicted_class"
    ] = rf_model.predict(
        X
    )


organic[
    "predicted_class_name"
] = np.where(

    organic[
        "predicted_class"
    ] == 1,

    "Artificially Amplified",

    "Organic"
)



print()
print(
    "Predicted classification distribution:"
)

print(
    organic[
        "predicted_class"
    ]
    .value_counts()
    .rename(
        index={
            0: "Organic",
            1: "Artificial"
        }
    )
)



# PART 34 — SHAP EXPLAINABILITY


print()
print("=" * 90)
print("PART 34 — SHAP EXPLAINABILITY")
print("=" * 90)

if BEST_CLASSIFIER == "XGBoost":

    shap_model = xgb_model

else:

    shap_model = rf_model


print(
    "Creating SHAP TreeExplainer..."
)

shap_explainer = shap.TreeExplainer(
    shap_model
)

# Limit SHAP computation if dataset becomes large

SHAP_SAMPLE_SIZE = min(
    300,
    len(X_test)
)

X_shap = (
    X_test
    .sample(
        n=SHAP_SAMPLE_SIZE,
        random_state=42
    )
)

shap_values = (
    shap_explainer
    .shap_values(
        X_shap
    )
)


# Handle different SHAP output formats

if isinstance(
    shap_values,
    list
):

    if len(shap_values) == 2:

        shap_values_for_positive = (
            shap_values[1]
        )

    else:

        shap_values_for_positive = (
            shap_values[0]
        )

else:

    shap_values_for_positive = (
        shap_values
    )


print(
    "✓ SHAP values calculated"
)


# SHAP feature importance

shap_importance = pd.DataFrame({

    "feature": X_shap.columns,

    "mean_absolute_shap": np.abs(
        shap_values_for_positive
    ).mean(
        axis=0
    )
})

shap_importance = (
    shap_importance
    .sort_values(
        "mean_absolute_shap",
        ascending=False
    )
    .reset_index(
        drop=True
    )
)

print()
print(
    "SHAP FEATURE IMPORTANCE"
)

print(
    shap_importance
    .to_string(
        index=False
    )
)


# Save SHAP importance

shap_importance_path = (
    "/content/reddit_shap_feature_importance.csv"
)

shap_importance.to_csv(
    shap_importance_path,
    index=False
)

print(
    "✓ Saved:",
    shap_importance_path
)


# SHAP plot

plt.figure(
    figsize=(10, 7)
)

shap.summary_plot(
    shap_values_for_positive,
    X_shap,
    show=False
)

plt.tight_layout()

shap_summary_path = (
    "/content/shap_summary_plot.png"
)

plt.savefig(
    shap_summary_path,
    dpi=300,
    bbox_inches="tight"
)

plt.show()

print(
    "✓ Saved:",
    shap_summary_path
)



# PART 35 — ADD SHAP VALUES TO TEST DATA


print()
print("=" * 90)
print("PART 35 — SHAP VALUES PER FEATURE")
print("=" * 90)

shap_value_columns = []

for feature in X_shap.columns:

    safe_name = re.sub(
        r"[^A-Za-z0-9_]+",
        "_",
        feature
    )

    column_name = (
        "SHAP_"
        + safe_name
    )

    shap_value_columns.append(
        column_name
    )

    organic.loc[
        X_shap.index,
        column_name
    ] = (
        shap_values_for_positive[
            :,
            X_shap.columns.get_loc(
                feature
            )
        ]
    )



# PART 36 — LIME EXPLAINABILITY


print()
print("=" * 90)
print("PART 36 — LIME EXPLAINABILITY")
print("=" * 90)

lime_explainer = (
    LimeTabularExplainer(

        training_data=X_train.values,

        feature_names=FEATURE_COLUMNS,

        class_names=[
            "Organic",
            "Artificial"
        ],

        mode="classification",

        discretize_continuous=True,

        random_state=42
    )
)


def lime_prediction_function(
    values
):

    values_df = pd.DataFrame(
        values,
        columns=FEATURE_COLUMNS
    )

    if BEST_CLASSIFIER == "XGBoost":

        return xgb_model.predict_proba(
            values_df
        )

    return rf_model.predict_proba(
        values_df
    )


# Explain first test instance

lime_instance_index = X_test.index[0]

lime_instance = (
    X_test.loc[
        lime_instance_index
    ]
    .values
)

lime_explanation = (
    lime_explainer.explain_instance(

        lime_instance,

        lime_prediction_function,

        num_features=len(
            FEATURE_COLUMNS
        )
    )
)


lime_records = []

for feature, weight in (
    lime_explanation
    .as_list()
):

    lime_records.append({

        "feature": feature,

        "weight": weight,

        "direction": (
            "Artificial"
            if weight > 0
            else "Organic"
        )
    })


lime_df = pd.DataFrame(
    lime_records
)

print()
print(
    "LIME EXPLANATION"
)

print(
    lime_df
    .to_string(
        index=False
    )
)


lime_path = (
    "/content/reddit_lime_explanation.csv"
)

lime_df.to_csv(
    lime_path,
    index=False
)

print()
print(
    "✓ Saved:",
    lime_path
)



# PART 37 — ORGANIC / ARTIFICIAL TREND SUMMARY


print()
print("=" * 90)
print("PART 37 — ORGANIC / ARTIFICIAL TREND SUMMARY")
print("=" * 90)

organic_summary = (
    organic
    .groupby(
        [
            "topic_id",
            "topic_name"
        ]
    )
    .agg(

        post_count=(
            "post_id",
            "count"
        ),

        artificial_probability=(
            "predicted_probability_artificial",
            "mean"
        ),

        artificial_posts=(
            "predicted_class",
            "sum"
        ),

        average_engagement=(
            "feature_engagement",
            "mean"
        ),

        average_sentiment=(
            "sentiment_score",
            "mean"
        ),

        amplification_score=(
            "amplification_score",
            "mean"
        )
    )
    .reset_index()
)


organic_summary[
    "organic_probability"
] = (
    1
    -
    organic_summary[
        "artificial_probability"
    ]
)

organic_summary[
    "trend_origin"
] = np.where(

    organic_summary[
        "artificial_probability"
    ] >= 0.5,

    "Artificially Amplified",

    "Organic"
)


# Merge trend score

organic_summary = organic_summary.merge(

    ranking[
        [
            "topic_id",
            "trend_score",
            "trend_category",
            "rank"
        ]
    ],

    on="topic_id",

    how="left"
)

organic_summary = (
    organic_summary
    .sort_values(
        "trend_score",
        ascending=False
    )
)


print(
    organic_summary[
        [
            "rank",
            "topic_name",
            "trend_score",
            "trend_category",
            "trend_origin",
            "artificial_probability",
            "organic_probability"
        ]
    ]
    .head(20)
    .to_string(
        index=False
    )
)



# PART 38 — EXPLAINABLE TREND ANALYSIS


print()
print("=" * 90)
print("PART 38 — EXPLAINABLE TREND ANALYSIS")
print("=" * 90)

analysis = topic_stats.copy()

analysis[
    "frequency_contribution"
] = (
    analysis[
        "frequency_score"
    ]
    * 30
)

analysis[
    "growth_contribution"
] = (
    analysis[
        "growth_score"
    ]
    * 30
)

analysis[
    "engagement_contribution"
] = (
    analysis[
        "engagement_score"
    ]
    * 25
)

analysis[
    "sentiment_contribution"
] = (
    analysis[
        "sentiment_score"
    ]
    * 15
)


# Add organic/artificial information

analysis = analysis.merge(

    organic_summary[
        [
            "topic_id",
            "artificial_probability",
            "organic_probability",
            "trend_origin"
        ]
    ],

    on="topic_id",

    how="left"
)


analysis[
    "sentiment_direction"
] = np.where(

    analysis[
        "average_sentiment"
    ] > 0.05,

    "Positive",

    np.where(

        analysis[
            "average_sentiment"
        ] < -0.05,

        "Negative",

        "Neutral"
    )
)


analysis[
    "explanation"
] = (

    "Trend score combines topic frequency "
    "(30%), recent growth (30%), engagement "
    "(25%) and sentiment (15%). Organic/artificial "
    "classification uses engagement, score, "
    "comment activity, repetition and temporal "
    "burst signals, with SHAP and LIME used to "
    "explain machine-learning predictions."
)


analysis = (
    analysis
    .sort_values(
        "trend_score",
        ascending=False
    )
    .reset_index(
        drop=True
    )
)

analysis["rank"] = (
    np.arange(
        1,
        len(analysis) + 1
    )
)



# PART 39 — TREND INSIGHTS


print()
print("=" * 90)
print("PART 39 — TREND INSIGHTS")
print("=" * 90)

insights = []

for _, row in ranking.iterrows():

    topic_id = row[
        "topic_id"
    ]

    topic_name = row[
        "topic_name"
    ]

    score = row[
        "trend_score"
    ]

    category = row[
        "trend_category"
    ]

    posts = row[
        "post_count"
    ]

    growth = row[
        "growth_rate"
    ]

    engagement = row[
        "total_engagement"
    ]

    sentiment = row[
        "average_sentiment"
    ]

    if sentiment > 0.05:

        sentiment_text = "positive"

    elif sentiment < -0.05:

        sentiment_text = "negative"

    else:

        sentiment_text = "neutral"


    if growth > 0:

        growth_text = (
            f"activity increased by "
            f"approximately {growth:.0f} "
            f"posts in the latest observed week"
        )

    elif growth < 0:

        growth_text = (
            f"activity decreased by "
            f"approximately {abs(growth):.0f} "
            f"posts in the latest observed week"
        )

    else:

        growth_text = (
            "activity remained broadly stable"
        )


    origin_row = organic_summary[
        organic_summary[
            "topic_id"
        ]
        ==
        topic_id
    ]

    if len(origin_row) > 0:

        artificial_probability = (
            origin_row[
                "artificial_probability"
            ].iloc[0]
        )

    else:

        artificial_probability = np.nan


    if (
        not np.isnan(
            artificial_probability
        )
        and
        artificial_probability >= 0.5
    ):

        origin_text = (
            "The topic shows evidence of "
            "artificial amplification."
        )

    else:

        origin_text = (
            "The topic is more consistent "
            "with organic consumer activity."
        )


    insight = (

        f"'{topic_name}' is ranked as a "
        f"{category.lower()} with a trend "
        f"score of {score:.2f}. "

        f"The topic generated {posts} posts "
        f"and {engagement:.0f} total engagement. "

        f"{growth_text}. "

        f"Overall sentiment was "
        f"{sentiment_text}. "

        f"{origin_text}"
    )


    insights.append({

        "rank": row["rank"],

        "topic_id": topic_id,

        "topic_name": topic_name,

        "trend_score": score,

        "trend_category": category,

        "artificial_probability":
            artificial_probability,

        "insight": insight
    })


insights_df = pd.DataFrame(
    insights
)



# PART 40 — WEEKLY TOPIC ACTIVITY


weekly_activity = (
    reddit_topic
    .groupby(
        [
            "week",
            "topic_id",
            "topic_name"
        ]
    )
    .agg(

        post_count=(
            "topic_id",
            "size"
        ),

        total_engagement=(
            "engagement_positive",
            "sum"
        ),

        average_engagement=(
            "engagement_positive",
            "mean"
        ),

        average_sentiment=(
            "sentiment_score",
            "mean"
        )
    )
    .reset_index()
)

weekly_activity = (
    weekly_activity
    .sort_values(
        [
            "week",
            "topic_id"
        ]
    )
)



# PART 41 — SENTIMENT OVER TIME


sentiment_over_time = (
    reddit_topic
    .groupby(
        [
            "week",
            "topic_id",
            "topic_name"
        ]
    )
    .agg(

        post_count=(
            "topic_id",
            "size"
        ),

        average_sentiment=(
            "sentiment_score",
            "mean"
        ),

        positive_posts=(
            "sentiment",
            lambda x:
            (
                x == "Positive"
            ).sum()
        ),

        neutral_posts=(
            "sentiment",
            lambda x:
            (
                x == "Neutral"
            ).sum()
        ),

        negative_posts=(
            "sentiment",
            lambda x:
            (
                x == "Negative"
            ).sum()
        )
    )
    .reset_index()
)

sentiment_over_time[
    "date"
] = pd.to_datetime(
    sentiment_over_time[
        "week"
    ],
    errors="coerce"
)

sentiment_over_time = (
    sentiment_over_time[
        [
            "date",
            "topic_id",
            "topic_name",
            "post_count",
            "average_sentiment",
            "positive_posts",
            "neutral_posts",
            "negative_posts"
        ]
    ]
    .sort_values(
        "date"
    )
)



# PART 42 — SAVE ALL OUTPUT FILES


print()
print("=" * 90)
print("PART 42 — SAVING OUTPUT FILES")
print("=" * 90)

ranking_path = (
    "/content/reddit_final_trend_ranking.csv"
)

analysis_path = (
    "/content/reddit_explainable_trend_analysis.csv"
)

insights_path = (
    "/content/reddit_final_trend_insights.csv"
)

sentiment_path = (
    "/content/reddit_topic_sentiment_over_time.csv"
)

weekly_path = (
    "/content/reddit_weekly_topic_activity.csv"
)

organic_post_path = (
    "/content/reddit_organic_artificial_predictions.csv"
)

organic_summary_path = (
    "/content/reddit_organic_artificial_topic_summary.csv"
)

model_comparison_path = (
    "/content/reddit_xgboost_vs_random_forest.csv"
)

topic_info_path = (
    "/content/reddit_bertopic_topic_information.csv"
)

processed_path = (
    "/content/reddit_complete_analysis.csv"
)


ranking.to_csv(
    ranking_path,
    index=False
)

analysis.to_csv(
    analysis_path,
    index=False
)

insights_df.to_csv(
    insights_path,
    index=False
)

sentiment_over_time.to_csv(
    sentiment_path,
    index=False
)

weekly_activity.to_csv(
    weekly_path,
    index=False
)

organic.to_csv(
    organic_post_path,
    index=False
)

organic_summary.to_csv(
    organic_summary_path,
    index=False
)

model_comparison.to_csv(
    model_comparison_path,
    index=False
)

topic_info.to_csv(
    topic_info_path,
    index=False
)

reddit.to_csv(
    processed_path,
    index=False
)


print("✓", ranking_path)
print("✓", analysis_path)
print("✓", insights_path)
print("✓", sentiment_path)
print("✓", weekly_path)
print("✓", organic_post_path)
print("✓", organic_summary_path)
print("✓", model_comparison_path)
print("✓", topic_info_path)
print("✓", processed_path)


# PART 43 — STREAMLIT DASHBOARD


print()
print("=" * 90)
print("PART 43 — CREATING STREAMLIT DASHBOARD")
print("=" * 90)

APP_PATH = (
    "/content/app.py"
)

app_code = r'''
import os
import pandas as pd
import numpy as np
import streamlit as st
import plotly.express as px


st.set_page_config(
    page_title="Explainable AI Reddit Trend Detection",
    page_icon="📊",
    layout="wide"
)


st.title(
    "📊 Explainable AI Framework for Reddit Consumer Trend Detection"
)

st.subheader(
    "Dashboard"
)

st.write(
    """
This dashboard presents Reddit consumer trend detection
using BERTopic, transformer sentiment analysis, temporal
trend analysis and machine-learning classification of
organic versus artificially amplified trends.
"""
)


BASE = "/content"


FILES = {

    "ranking":
        os.path.join(
            BASE,
            "reddit_final_trend_ranking.csv"
        ),

    "analysis":
        os.path.join(
            BASE,
            "reddit_explainable_trend_analysis.csv"
        ),

    "insights":
        os.path.join(
            BASE,
            "reddit_final_trend_insights.csv"
        ),

    "sentiment":
        os.path.join(
            BASE,
            "reddit_topic_sentiment_over_time.csv"
        ),

    "weekly":
        os.path.join(
            BASE,
            "reddit_weekly_topic_activity.csv"
        ),

    "organic":
        os.path.join(
            BASE,
            "reddit_organic_artificial_topic_summary.csv"
        ),

    "models":
        os.path.join(
            BASE,
            "reddit_xgboost_vs_random_forest.csv"
        )
}


missing = [

    name

    for name, path in FILES.items()

    if not os.path.exists(path)

]


if missing:

    st.error(
        "Required files are missing."
    )

    st.write(
        missing
    )

    st.stop()


ranking = pd.read_csv(
    FILES["ranking"]
)

analysis = pd.read_csv(
    FILES["analysis"]
)

insights = pd.read_csv(
    FILES["insights"]
)

sentiment = pd.read_csv(
    FILES["sentiment"]
)

weekly = pd.read_csv(
    FILES["weekly"]
)

organic = pd.read_csv(
    FILES["organic"]
)

models = pd.read_csv(
    FILES["models"]
)



# SIDEBAR


st.sidebar.header(
    "Dashboard Controls"
)


topics = [

    "All Topics"

] + sorted(

    ranking[
        "topic_name"
    ]
    .dropna()
    .astype(str)
    .unique()
    .tolist()

)


selected_topic = st.sidebar.selectbox(
    "Select Topic",
    topics
)



# FILTER


if selected_topic != "All Topics":

    ranking_view = ranking[
        ranking[
            "topic_name"
        ]
        ==
        selected_topic
    ].copy()

else:

    ranking_view = ranking.copy()



# KPI


st.header(
    "📌 Key Indicators"
)

col1, col2, col3, col4 = st.columns(4)


with col1:

    st.metric(
        "Topics Detected",
        len(ranking)
    )


with col2:

    st.metric(
        "Total Posts",
        int(
            ranking[
                "post_count"
            ].sum()
        )
    )


with col3:

    st.metric(
        "Top Trend Score",
        f"{ranking['trend_score'].max():.2f}"
    )


with col4:

    st.metric(
        "Best Classifier",
        "XGBoost"
        if models.loc[
            models["F1"].idxmax(),
            "Model"
        ] == "XGBoost"
        else "Random Forest"
    )



# TREND RANKING


st.header(
    "🏆 Consumer Trend Ranking"
)

st.dataframe(
    ranking_view[
        [
            "rank",
            "topic_name",
            "post_count",
            "growth_rate",
            "average_engagement",
            "average_sentiment",
            "trend_score",
            "trend_category"
        ]
    ],
    use_container_width=True,
    hide_index=True
)



# TREND SCORE


st.header(
    "📈 Explainable Trend Scores"
)

chart_data = (
    ranking_view
    .sort_values(
        "trend_score",
        ascending=True
    )
)

fig = px.bar(

    chart_data,

    x="trend_score",

    y="topic_name",

    orientation="h",

    title="Explainable Consumer Trend Score",

    labels={
        "trend_score": "Trend Score",
        "topic_name": "Topic"
    }
)

st.plotly_chart(
    fig,
    use_container_width=True
)



# ORGANIC VS ARTIFICIAL


st.header(
    "🤖 Organic vs Artificially Amplified Trends"
)

organic_view = organic.copy()

if selected_topic != "All Topics":

    organic_view = organic_view[
        organic_view[
            "topic_name"
        ]
        ==
        selected_topic
    ]


if len(organic_view) > 0:

    fig = px.bar(

        organic_view,

        x="topic_name",

        y=[
            "organic_probability",
            "artificial_probability"
        ],

        barmode="group",

        title="Organic vs Artificial Trend Probability",

        labels={
            "value": "Probability",
            "topic_name": "Topic"
        }
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )



# MODEL COMPARISON


st.header(
    "🧪 XGBoost vs Random Forest"
)

st.dataframe(
    models,
    use_container_width=True,
    hide_index=True
)


model_plot = models.melt(
    id_vars=["Model"],
    value_vars=[
        "Accuracy",
        "Precision",
        "Recall",
        "F1",
        "ROC_AUC"
    ],
    var_name="Metric",
    value_name="Score"
)

fig = px.bar(

    model_plot,

    x="Metric",

    y="Score",

    color="Model",

    barmode="group",

    title="Machine Learning Model Performance"
)

st.plotly_chart(
    fig,
    use_container_width=True
)



# WEEKLY ACTIVITY


st.header(
    "📊 Weekly Topic Activity"
)

weekly_view = weekly.copy()

if selected_topic != "All Topics":

    weekly_view = weekly_view[
        weekly_view[
            "topic_name"
        ]
        ==
        selected_topic
    ]


if len(weekly_view) > 0:

    fig = px.line(

        weekly_view,

        x="week",

        y="post_count",

        color="topic_name",

        markers=True,

        title="Weekly Topic Activity"
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )



# SENTIMENT OVER TIME


st.header(
    "😊 Sentiment Over Time"
)

sentiment_view = sentiment.copy()

if selected_topic != "All Topics":

    sentiment_view = sentiment_view[
        sentiment_view[
            "topic_name"
        ]
        ==
        selected_topic
    ]


if len(sentiment_view) > 0:

    fig = px.line(

        sentiment_view,

        x="date",

        y="average_sentiment",

        color="topic_name",

        markers=True,

        title="Average Sentiment Over Time"
    )

    fig.add_hline(
        y=0,
        line_dash="dash"
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )



# EXPLAINABLE INSIGHTS


st.header(
    "💡 Explainable Trend Insights"
)

if selected_topic != "All Topics":

    insight_view = insights[
        insights[
            "topic_name"
        ]
        ==
        selected_topic
    ]

else:

    insight_view = insights


for _, row in (
    insight_view
    .head(10)
    .iterrows()
):

    st.markdown(

        f"""
### Rank {int(row['rank'])}: {row['topic_name']}

**Trend category:** {row['trend_category']}

**Trend score:** {row['trend_score']:.2f}

**Artificial amplification probability:**
{row['artificial_probability']:.2f}

{row['insight']}
"""
    )



# METHODOLOGY


st.header(
    "🧠 Methodology"
)

st.markdown(
    """
### Topic Modelling

BERTopic identifies semantically related consumer
discussion topics using transformer embeddings,
UMAP dimensionality reduction and HDBSCAN clustering.

### Sentiment Analysis

Two transformer-based sentiment approaches were compared:

- BERT
- RoBERTa

Because the Reddit dataset does not contain human-labelled
sentiment ground truth, confidence, sentiment distribution
and model agreement are used as diagnostic measures rather
than falsely reporting classification accuracy.

### Trend Detection

The explainable trend score combines:

- Topic frequency — 30%
- Topic growth — 30%
- Engagement — 25%
- Sentiment — 15%

### Organic vs Artificial Classification

Machine-learning models classify trends using social-signal
features including engagement, score, comment activity,
text repetition and temporal bursts.

Random Forest and XGBoost are compared using:

- Accuracy
- Precision
- Recall
- F1-score
- ROC-AUC

### Explainable AI

SHAP provides global and local feature contribution
information for the tree-based classifiers.

LIME provides a local explanation for an individual
organic/artificial prediction.
"""
)


st.divider()

st.caption(
    "Explainable AI Framework for Reddit Consumer Trend Detection"
)
'''


with open(
    APP_PATH,
    "w",
    encoding="utf-8"
) as file:

    file.write(
        app_code
    )


print(
    "✓ Streamlit app created:",
    APP_PATH
)



# PART 44 — FINAL VALIDATION


print()
print("=" * 90)
print("PART 44 — FINAL VALIDATION")
print("=" * 90)

required_outputs = [

    sentiment_comparison_path,

    ranking_path,

    analysis_path,

    insights_path,

    sentiment_path,

    weekly_path,

    organic_post_path,

    organic_summary_path,

    model_comparison_path,

    topic_info_path,

    processed_path,

    shap_importance_path,

    shap_summary_path,

    lime_path,

    APP_PATH
]


all_outputs_exist = True

for path in required_outputs:

    if os.path.exists(path):

        size = os.path.getsize(
            path
        )

        print(
            f"✓ {os.path.basename(path):55s}"
            f"{size:,} bytes"
        )

    else:

        print(
            f"❌ {os.path.basename(path):55s}"
            "MISSING"
        )

        all_outputs_exist = False



# PART 45 — FINAL RESEARCH QUESTION RESULTS


print()
print("=" * 90)
print("PART 45 — RESEARCH QUESTION RESULTS")
print("=" * 90)

print()
print("RQ1 — BERTopic")
print(
    "Number of meaningful topics:",
    len(valid_topic_ids)
)

print(
    "Outlier posts:",
    int(
        (
            reddit["topic_id"]
            == -1
        ).sum()
    )
)


print()
print("RQ2 — BERT vs RoBERTa")

print(
    "BERT mean confidence:",
    round(
        bert_mean_confidence,
        4
    )
)

print(
    "RoBERTa mean confidence:",
    round(
        roberta_mean_confidence,
        4
    )
)

print(
    "Model agreement:",
    round(
        agreement_rate,
        2
    ),
    "%"
)

print(
    "Selected diagnostic model:",
    BEST_MODEL
)




print()
print("RQ3 — XGBoost vs Random Forest")

print(
    model_comparison
    .to_string(
        index=False
    )
)

print()
print(
    "Best classifier:",
    BEST_CLASSIFIER
)



# PART 46 — FINAL CLASSIFICATION DISTRIBUTION


print()
print(
    "FINAL ORGANIC / ARTIFICIAL PREDICTIONS"
)

print(
    organic[
        "predicted_class_name"
    ]
    .value_counts()
)



# PART 47 — FINAL MESSAGE


print()
print("=" * 90)

print("=" * 90)

if all_outputs_exist:

    print(
        """
✓ DATA CLEANING COMPLETED

✓ BERT SENTIMENT COMPLETED

✓ RoBERTa SENTIMENT COMPLETED

✓ BERT VS RoBERTa COMPARISON COMPLETED

✓ BERTopic COMPLETED

✓ TOPIC INTERPRETATION COMPLETED

✓ TEMPORAL TREND ANALYSIS COMPLETED

✓ EXPLAINABLE TREND SCORING COMPLETED

✓ ORGANIC / ARTIFICIAL CLASSIFICATION COMPLETED

✓ RANDOM FOREST COMPLETED

✓ XGBOOST COMPLETED

✓ SHAP EXPLAINABILITY COMPLETED

✓ LIME EXPLAINABILITY COMPLETED

✓ DASHBOARD OUTPUTS CREATED

✓ STREAMLIT DASHBOARD CREATED
"""
    )

else:

    print(
        "⚠ Some output files are missing."
    )


print()
print(
    "BEST SENTIMENT DIAGNOSTIC:",
    BEST_MODEL
)

print(
    "BEST ORGANIC/ARTIFICIAL CLASSIFIER:",
    BEST_CLASSIFIER
)

print()

print()
print(
    "Streamlit dashboard:"
)

print(
    "/content/app.py"
)

print()
print(
    "To run the dashboard in Colab:"
)

print(
    """
!pkill -f "streamlit run" || true
!streamlit run /content/app.py --server.port 8501 --server.address 0.0.0.0 --server.headless true --server.enableCORS false --server.enableXsrfProtection false --browser.gatherUsageStats false > /content/streamlit.log 2>&1 &
"""
)

print()
print("=" * 90)
print("ALL DONE")
print("=" * 90)

!pkill -f "streamlit run" || true
!streamlit run /content/app.py --server.port 8501 --server.address 0.0.0.0 --server.headless true --server.enableCORS false --server.enableXsrfProtection false --browser.gatherUsageStats false > /content/streamlit.log 2>&1 &

# ============================================================
# COLAB STREAMLIT — CLICKABLE LINK
# ============================================================

!pip install -q streamlit

import os
import subprocess
import time

APP = "/content/app.py"
PORT = 8501

if not os.path.exists(APP):
    raise FileNotFoundError(
        "❌ /content/app.py does not exist. "
        "The dashboard has not been created yet."
    )

# Stop old Streamlit processes
subprocess.run(
    "pkill -9 -f 'streamlit' || true",
    shell=True
)

time.sleep(2)

# Start Streamlit
process = subprocess.Popen(
    [
        "streamlit",
        "run",
        APP,
        "--server.port=8501",
        "--server.address=0.0.0.0",
        "--server.headless=true",
        "--server.enableCORS=false",
        "--server.enableXsrfProtection=false",
        "--browser.gatherUsageStats=false"
    ],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL
)

time.sleep(8)

# ============================================================
# CREATE COLAB CLICKABLE LINK
# ============================================================

from google.colab.output import eval_js
from IPython.display import display, HTML

try:

    url = eval_js(
        "google.colab.kernel.proxyPort(8501)"
    )

    print("=" * 70)
    print("✅ STREAMLIT DASHBOARD IS RUNNING")
    print("=" * 70)
    print()
    print("Dashboard URL:")
    print(url)
    print()

    display(
        HTML(
            f'''
            <a href="{url}" target="_blank"
               style="
               display:inline-block;
               padding:12px 20px;
               background:#ff4b4b;
               color:white;
               text-decoration:none;
               border-radius:8px;
               font-weight:bold;
               font-size:16px;">
               🚀 OPEN STREAMLIT DASHBOARD
            </a>
            '''
        )
    )

except Exception as e:

    print("❌ Could not generate Colab proxy link.")
    print("Error:", e)

    print()
    print("Try opening:")
    print("http://localhost:8501")

# ============================================================
# CREATE ONE ZIP FILE CONTAINING ALL DISSERTATION OUTPUTS
# ============================================================

import os
import zipfile
from google.colab import files

print("=" * 80)
print("CREATING DISSERTATION OUTPUT ZIP FILE")
print("=" * 80)

# ------------------------------------------------------------
# ZIP FILE NAME
# ------------------------------------------------------------

ZIP_PATH = "/content/reddit_dissertation_all_outputs.zip"

# Remove an older ZIP if it exists
if os.path.exists(ZIP_PATH):
    os.remove(ZIP_PATH)

# ------------------------------------------------------------
# FILES TO INCLUDE
# ------------------------------------------------------------

output_files = [
    # Sentiment analysis
    "reddit_sentiment_comparison.csv",

    # BERTopic / trend analysis
    "reddit_final_trend_ranking.csv",
    "reddit_explainable_trend_analysis.csv",
    "reddit_final_trend_insights.csv",
    "reddit_topic_sentiment_over_time.csv",
    "reddit_weekly_topic_activity.csv",

    # Complete processed dataset
    "reddit_complete_analysis.csv",

    # Organic vs Artificial trend detection
    "reddit_organic_artificial_predictions.csv",
    "reddit_organic_artificial_model_comparison.csv",
    "reddit_organic_artificial_features.csv",

    # Explainability
    "shap_feature_importance.csv",
    "shap_explanations.csv",
    "lime_explanations.csv",

    # Model outputs
    "xgboost_predictions.csv",
    "random_forest_predictions.csv",

    # Dashboard
    "app.py",

    # Logs
    "streamlit.log"
]

# ------------------------------------------------------------
# ALSO INCLUDE GENERATED PNG / HTML / JSON FILES
# ------------------------------------------------------------

for filename in os.listdir("/content"):

    if filename.lower().endswith(
        (
            ".png",
            ".jpg",
            ".jpeg",
            ".html",
            ".json",
            ".txt"
        )
    ):

        if filename not in output_files:
            output_files.append(filename)

# ------------------------------------------------------------
# CREATE ZIP
# ------------------------------------------------------------

added_files = []
missing_files = []

with zipfile.ZipFile(
    ZIP_PATH,
    "w",
    compression=zipfile.ZIP_DEFLATED
) as zipf:

    for filename in output_files:

        filepath = os.path.join(
            "/content",
            filename
        )

        if os.path.isfile(filepath):

            zipf.write(
                filepath,
                arcname=filename
            )

            added_files.append(filename)

        else:

            missing_files.append(filename)

# ------------------------------------------------------------
# DISPLAY RESULTS
# ------------------------------------------------------------

print()
print("=" * 80)
print("ZIP CREATION COMPLETE")
print("=" * 80)

print()
print(f"ZIP FILE:")
print(ZIP_PATH)

print()
print(f"Files included: {len(added_files)}")

for filename in added_files:
    print("✓", filename)

if missing_files:

    print()
    print("=" * 80)
    print("FILES NOT FOUND")
    print("=" * 80)

    for filename in missing_files:
        print("⚠", filename)

# ------------------------------------------------------------
# ZIP SIZE
# ------------------------------------------------------------

zip_size = os.path.getsize(ZIP_PATH)

print()
print("=" * 80)
print("ZIP INFORMATION")
print("=" * 80)

print(
    f"Size: {zip_size / (1024 * 1024):.2f} MB"
)

print()
print("✓ ZIP READY")
print()

# ------------------------------------------------------------
# DOWNLOAD
# ------------------------------------------------------------

files.download(ZIP_PATH)

